from environs import Env

env = Env()
env.read_env()


PNL_BOUND = env.float('PNL_BOUND')
ROI_BOUND = env.float("ROI_BOUND")
WIN_RATE_BOUND = env.float("WIN_RATE_BOUND")
TRADEWAGON_PROFILES_TO_FETCH = env.int("TRADEWAGON_PROFILES_TO_FETCH")
COLLECTOR_HOST = env.str("COLLECTOR_HOST")
COLLECTOR_PORT = env.int("COLLECTOR_PORT")
IDEAS_INTERVAL_UPDATE = env.int("IDEAS_INTERVAL_UPDATE")
TRADERS_INTERVAL_UPDATE = env.int("TRADERS_INTERVAL_UPDATE")
