#name: CI
#on:
#  workflow_run:
#      workflows: [Python application]
#      branches: [main]
#      types:
#        - completed
#
#jobs:
#
#  push-image-to-docker-hub:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-latest
#    env:
#      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#
#    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:latest
#          secrets: |
#            GIT_AUTH_TOKEN=${{ secrets.GIT_TOKEN }}
